name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Display Xcode Version
        run: xcodebuild -version

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Display Swift Version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run Tests
        run: swift test